#! /usr/bin/env python3
import subprocess, sys
title = subprocess.getoutput(f"playerctl metadata title --player={sys.argv[1]}")

player = sys.argv[1]

if len(title) > 20:
    title = f"{title[:20]}..."

print(title)