#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

$HOME/.config/bspwm/scripts/rules &
$HOME/.config/bspwm/scripts/autostarts &

#rm $HOME/.config/dunst/notifLog &&
#touch $HOME/.config/dunst/notifLog &&

#$HOME/.config/bspwm/scripts/logNotifs $HOME/.config/dunst/notifLog &
