#!/bin/sh

# === AUTOSTARTS === #
(killall lxsession && lxsession) || lxsession &

(killall xcompmgr && xcompmgr -F -f -I 0.05 -O 0.05 -r 12) || xcompmgr -F -f -I 0.05 -O 0.05 -r 12 &

(killall blueman-applet && blueman-applet) || blueman-applet &
(killall flameshot && flameshot) || flameshot &
nitrogen --restore &
(killall unclutter && unclutter) || unclutter &
(killall nm-applet && nm-applet) || nm-applet &

# (killall eww && eww daemon) || eww daemon &
(killall polybar && $HOME/.config/polybar/launch) || $HOME/.config/polybar/launch &

killall bspc &

libinput-gestures-setup stop &&
libinput-gestures-setup start &
