#!/bin/bash
# not used anywhere 
# i may use it later ¯\_(ツ)_/¯
logfile=$1

dbus-monitor "interface='org.freedesktop.Notifications'" |\
grep --line-buffered "string" |\
grep --line-buffered -e method -e ":" -e '""' -e urgency -e notify -v |\
grep --line-buffered '.*(?=string)|(?<=string).*' -oPi |\
grep --line-buffered -v '^\s*$' |\
xargs -I '{}' \
printf "---$( date '+%I:%M %p' )---\n"{}"\n" >> $logfile
