#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width            1
bspc config window_gap              12
bspc config normal_border_color     "#1e1e2e"
bspc config focused_border_color    "#cdd6f4"
bspc config presel_feedback_color   "#B5E8E0"

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config border_radius           5
bspc config top_padding             40

bspc rule -a mpv state=floating sticky=on
bspc rule -a Galculator state=floating sticky=on
bspc rule -a Font-manager state=floating sticky=on
bspc rule -a feh state=floating sticky=on
bspc rule -a zathura state=tiling sticky=on


# === AUTOSTARTS === #
nitrogen --restore &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
#$HOME/.config/polybar/launch.sh & 
nm-applet &
blueman-applet &
killall eww &
killall stalonetray &
nm-applet &
eww daemon 
eww open bar 
sleep 2
stalonetray -bg "#1e1e2e" --geometry 2x1+656+10 --max-geometry 2x1 --scrollbars horizontal &
