#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width            1
bspc config window_gap              12
bspc config normal_border_color     "#181825"
bspc config focused_border_color    "#313244"
bspc config presel_feedback_color   "#B5E8E0"

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config border_radius           5
#bspc config top_padding             35

#bspc rule -a "*" state=floating 
bspc rule -a mpv state=floating
bspc rule -a Galculator state=floating
bspc rule -a Font-manager state=floating
bspc rule -a feh state=floating 
bspc rule -a zathura state=tiling 


# === AUTOSTARTS === #
lxsession &
nitrogen --restore &
picom --config $HOME/.config/picom/picom.conf &
#$HOME/.config/polybar/launch.sh & 
nm-applet &
blueman-applet &
flameshot &
nm-applet &

pgrep -x eww > /dev/null || (eww daemon && eww open bar)

libinput-gestures-setup start &
